{{- range .Values.infra.dotnet_microservices }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-webapi
  labels:
    app: itec5905
spec:
  selector:
    matchLabels:
      app: itec5905
      tier: webapi
      app.kubernetes.io/name: {{ .name }}-webapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: itec5905
        tier: webapi
        app.kubernetes.io/name: {{ .name }}-webapi
    spec:
      containers:
      - image: ikemtz/itec5905-{{ .name }}-webapi:latest
        name: webapi
        env:
        - name: DbConnectionString
          valueFrom:
            secretKeyRef:
              name: mysql-{{ .name }}-creds
              key: dbConnectionString
        - name: REDIS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: redis-creds
              key: redisConnectionString
        ports:
        - name: webapi
          containerPort: 5000          
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - "bash" 
            - "-c"
            - "curl -f http://localhost:5000/healthz"
          initialDelaySeconds: 15
          periodSeconds: 60
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - "bash" 
            - "-c"
            - "curl -f http://localhost:5000/healthz"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 1
---
{{- end -}}
