{{- if .Values.environment.useIngress }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: itec5905-in
spec:
  rules:
    - host: {{ $.Values.environment.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-svc
                port:
                  number: 8080
---
{{- end -}}