{{- if .Values.environment.createVolumes }}
{{- range .Values.infra.dotnet_microservices }}
{{- if .hasDb }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .name }}-volume
spec:
  storageClassName: {{ $.Values.environment.storageClass }}
  capacity:
    storage: 1Gi
  accessModes:
    - {{ $.Values.environment.storageAccessMode }}
  claimRef:
    name: {{ .name }}-volume-claim
  hostPath:
    path: /c/tmp/{{ .name }}-volume
---
{{- end -}}
{{- end -}}
{{- end -}}