kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-volume
spec:
  storageClassName: {{$.Values.environment.storageClass}}
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: redis-volume-claim
  hostPath:
    path: /c/tmp/redis-volume
---