apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-volume-claim
spec:
  storageClassName: {{ $.Values.environment.storageClass }}
  accessModes:
    - {{ $.Values.environment.storageAccessMode }}
  resources:
    requests:
      storage: 1Gi
---