{{- range .Values.infra.dotnet_microservices }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
{{- end -}}