{{- if .Values.environment.useRoutes }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: itec5905
spec:
  to:
    kind: Service
    name: nginx-svc
    weight: 100
  port:
    targetPort: nginx
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
{{- end -}}