
FROM bitnami/mysql:latest
ARG DB_NAME
ENV DB_NAME=${DB_NAME}
ARG DOMAIN_NAME
ENV DOMAIN_NAME=${DOMAIN_NAME}

COPY ["ITEC5905.${DOMAIN_NAME}.Db/*.sql", "/docker-entrypoint-startdb.d/"]
ENV MYSQL_USER=dbUser
ENV MYSQL_PASSWORD=DockerRocks123!
ENV MYSQL_ROOT_PASSWORD=DockerRocks123!
ENV MYSQL_DATABASE=${DB_NAME}
