infra:
  dotnet_microservices:
    - name: artists
      hasDb: true
    - name: customers
      hasDb: true

environment:
  createVolumes: true
  storageClass: hostpath
  storageAccessMode: ReadWriteMany
  useRoutes: false