/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum AlbumSongProperties {
  ID = 'id',
  ALBUM_ID = 'albumId',
  SONG_ID = 'songId',
  UPDATE_COUNT = 'updateCount',
  ALBUM = 'album',
  SONG = 'song',
}
