/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { IArtistForm } from './artist.form';
import { IAlbumSongForm } from './album-song.form';
import { IPictureForm } from './picture.form';

export interface IAlbumForm {
    id: FormControl<string | null | undefined>;
    name: FormControl<string>;
    artistId: FormControl<string>;
    songCount: FormControl<number | null | undefined>;
    pictureId: FormControl<string | null | undefined>;
    updateCount: FormControl<number | null | undefined>;
    artist: FormGroup<IArtistForm>;
    songs: FormArray<FormGroup<IAlbumSongForm>>;
    picture: FormGroup<IPictureForm>;
}
