/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { AlbumSongProperties } from './album-song.properties';

export function createTestAlbumSong() {
    return { 
      [AlbumSongProperties.ID]: 'ID',
      [AlbumSongProperties.ALBUM_ID]: 'ALBUM_ID',
      [AlbumSongProperties.SONG_ID]: 'SONG_ID',
      [AlbumSongProperties.UPDATE_COUNT]: 0, 
      [AlbumSongProperties.ALBUM]: undefined,
      [AlbumSongProperties.SONG]: undefined,
    };
}
