/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum ArtistProperties {
  ID = 'id',
  NAME = 'name',
  STAGE_NAME = 'stageName',
  EMAIL = 'email',
  ALBUM_COUNT = 'albumCount',
  SONG_COUNT = 'songCount',
  PICTURE_TYPE = 'pictureType',
  PICTURE_IPFS_HASH = 'pictureIpfsHash',
  UPDATE_COUNT = 'updateCount',
  GENRES = 'genres',
  ALBUMS = 'albums',
  ARTIST_SONGS = 'artistSongs',
}
