/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { IArtistForm } from './artist.form';
import { ISongForm } from './song.form';

export interface IArtistSongForm {
    id: FormControl<string | null | undefined>;
    artistId: FormControl<string>;
    songId: FormControl<string>;
    index: FormControl<number | null | undefined>;
    updateCount: FormControl<number | null | undefined>;
    artist: FormGroup<IArtistForm>;
    song: FormGroup<ISongForm>;
}
