/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { IGenreForm } from './genre.form';
import { IArtistForm } from './artist.form';

export interface IArtistGenreForm {
    id: FormControl<string | null | undefined>;
    genreId: FormControl<string>;
    artistId: FormControl<string>;
    updateCount: FormControl<number | null | undefined>;
    genre: FormGroup<IGenreForm>;
    artist: FormGroup<IArtistForm>;
}
