/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { ArtistGenreUpsertRequestProperties } from './artist-genre-upsert-request.properties';

export function createTestArtistGenreUpsertRequest() {
    return { 
      [ArtistGenreUpsertRequestProperties.ID]: 'ID',
      [ArtistGenreUpsertRequestProperties.NAME]: 'NAME', 
    };
}
