/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { IGenre } from './genre.model';
import { IArtist } from './artist.model';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface IArtistGenre {
  id?: string | null;
  genreId?: string;
  artistId?: string;
  updateCount?: number | null;
  genre?: Partial<IGenre>;
  artist?: Partial<IArtist>;
}
