/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { ArtistUpsertRequestProperties } from './artist-upsert-request.properties';

export function createTestArtistUpsertRequest() {
    return { 
      [ArtistUpsertRequestProperties.ID]: 'ID',
      [ArtistUpsertRequestProperties.NAME]: 'NAME',
      [ArtistUpsertRequestProperties.STAGE_NAME]: 'STAGE_NAME',
      [ArtistUpsertRequestProperties.EMAIL]: 'artist-upsert-request@email.org',
      [ArtistUpsertRequestProperties.GENRES]: 'GENRES', 
    };
}
