/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IArtistGenreForm } from './artist-genre.form';
import { IGenreForm } from './genre.form';
import { GenreFormGroupFac } from './genre.form-group-fac';
import { IArtistForm } from './artist.form';
import { ArtistFormGroupFac } from './artist.form-group-fac';

export function ArtistGenreFormGroupFac(): FormGroup<IArtistGenreForm> {
  return new FormGroup<IArtistGenreForm>({
    id: new FormControl<string | null | undefined>(null),
    genreId: new FormControl<string>('', { validators: Validators.compose([Validators.required, Validators.minLength(1), Validators.maxLength(255)]), nonNullable: true }),
    artistId: new FormControl<string>('', { validators: Validators.required, nonNullable: true } ),
    updateCount: new FormControl<number | null | undefined>(null),
    genre: new FormGroup<IGenreForm>(GenreFormGroupFac().controls, { validators: Validators.required } ),
    artist: new FormGroup<IArtistForm>(ArtistFormGroupFac().controls),
  });
}
