/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum ArtistUpsertRequestProperties {
  ID = 'id',
  NAME = 'name',
  STAGE_NAME = 'stageName',
  EMAIL = 'email',
  PICTURE_IPFS_HASH = 'pictureIpfsHash',
  PICTURE_TYPE = 'pictureType',
  GENRES = 'genres',
}
