/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { ArtistGenreProperties } from './artist-genre.properties';

export function createTestArtistGenre() {
    return { 
      [ArtistGenreProperties.ID]: 'ID',
      [ArtistGenreProperties.GENRE_ID]: 'GENRE_ID',
      [ArtistGenreProperties.ARTIST_ID]: 'ARTIST_ID',
      [ArtistGenreProperties.UPDATE_COUNT]: 0, 
      [ArtistGenreProperties.GENRE]: undefined,
      [ArtistGenreProperties.ARTIST]: undefined,
    };
}
