/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum ArtistGenreProperties {
  ID = 'id',
  GENRE_ID = 'genreId',
  ARTIST_ID = 'artistId',
  UPDATE_COUNT = 'updateCount',
  GENRE = 'genre',
  ARTIST = 'artist',
}
