/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { ArtistProperties } from './artist.properties';

export function createTestArtist() {
    return { 
      [ArtistProperties.ID]: 'ID',
      [ArtistProperties.NAME]: 'NAME',
      [ArtistProperties.STAGE_NAME]: 'STAGE_NAME',
      [ArtistProperties.EMAIL]: 'artist@email.org',
      [ArtistProperties.ALBUM_COUNT]: 0,
      [ArtistProperties.SONG_COUNT]: 0,
      [ArtistProperties.PICTURE_ID]: 'PICTURE_ID',
      [ArtistProperties.UPDATE_COUNT]: 0, 
      [ArtistProperties.GENRES]: [],
      [ArtistProperties.ALBUMS]: [],
      [ArtistProperties.ARTIST_SONGS]: [],
      [ArtistProperties.PICTURE]: undefined,
    };
}
