/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #endpoints-ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum Endpoints {
  albums = 'artists-webapi/api/v1/Albums.json',
  artists = 'artists-webapi/api/v1/Artists.json',
  songs = 'artists-webapi/api/v1/Songs.json',
}
export interface IEndpoints {
  readonly albums: string;
  readonly artists: string;
  readonly songs: string;
}
