/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { GenreProperties } from './genre.properties';

export function createTestGenre() {
    return { 
      [GenreProperties.ID]: 'ID',
      [GenreProperties.UPDATE_COUNT]: 0, 
    };
}
