/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IGenreForm } from './genre.form';

export function GenreFormGroupFac(): FormGroup<IGenreForm> {
  return new FormGroup<IGenreForm>({
    id: new FormControl<string | null | undefined>(null, { validators: Validators.compose([Validators.minLength(1), Validators.maxLength(255)]) }),
    updateCount: new FormControl<number | null | undefined>(null),
  });
}
