/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #index.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export * from './album-song.form-group-fac';
export * from './album-song.form';
export * from './album-song.model';
export * from './album-song.properties';
export * from './album-song.test-obj-fac';
export * from './album.form-group-fac';
export * from './album.form';
export * from './album.model';
export * from './album.properties';
export * from './album.test-obj-fac';
export * from './artist-genre-upsert-request.form-group-fac';
export * from './artist-genre-upsert-request.form';
export * from './artist-genre-upsert-request.model';
export * from './artist-genre-upsert-request.properties';
export * from './artist-genre-upsert-request.test-obj-fac';
export * from './artist-genre.form-group-fac';
export * from './artist-genre.form';
export * from './artist-genre.model';
export * from './artist-genre.properties';
export * from './artist-genre.test-obj-fac';
export * from './artist-song.form-group-fac';
export * from './artist-song.form';
export * from './artist-song.model';
export * from './artist-song.properties';
export * from './artist-song.test-obj-fac';
export * from './artist-upsert-request.form-group-fac';
export * from './artist-upsert-request.form';
export * from './artist-upsert-request.model';
export * from './artist-upsert-request.properties';
export * from './artist-upsert-request.test-obj-fac';
export * from './artist.form-group-fac';
export * from './artist.form';
export * from './artist.model';
export * from './artist.properties';
export * from './artist.test-obj-fac';
export * from './problem-details.form-group-fac';
export * from './problem-details.form';
export * from './problem-details.model';
export * from './problem-details.properties';
export * from './problem-details.test-obj-fac';
export * from './song.form-group-fac';
export * from './song.form';
export * from './song.model';
export * from './song.properties';
export * from './song.test-obj-fac';
