/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IPictureForm } from './picture.form';

export function PictureFormGroupFac(): FormGroup<IPictureForm> {
  return new FormGroup<IPictureForm>({
    id: new FormControl<string | null | undefined>(null),
    blob: new FormControl<string>('', { validators: Validators.compose([Validators.required, Validators.maxLength(100000000)]), nonNullable: true }),
    type: new FormControl<string>('', { validators: Validators.compose([Validators.required, Validators.minLength(1), Validators.maxLength(5)]), nonNullable: true }),
    updateCount: new FormControl<number | null | undefined>(null),
  });
}
