/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { PictureProperties } from './picture.properties';

export function createTestPicture() {
    return { 
      [PictureProperties.ID]: 'ID',
      [PictureProperties.REFERENCE_ID]: 'REFERENCE_ID',
      [PictureProperties.BLOB]: 'BLOB',
      [PictureProperties.TYPE]: 'TYPE',
      [PictureProperties.UPDATE_COUNT]: 0, 
    };
}
