/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum PictureProperties {
  ID = 'id',
  REFERENCE_ID = 'referenceId',
/**
 * Max length is 1 Megabyte
 */
  BLOB = 'blob',
  TYPE = 'type',
  UPDATE_COUNT = 'updateCount',
}
