/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum SongUpsertRequestProperties {
  ID = 'id',
  NAME = 'name',
  ALBUM_IDS = 'albumIds',
  ARTIST_IDS = 'artistIds',
  GENRE_ID = 'genreId',
  IPFS_HASH = 'ipfsHash',
  PICTURE_IPFS_HASH = 'pictureIpfsHash',
  PICTURE_TYPE = 'pictureType',
}
