/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum SongProperties {
  ID = 'id',
  NAME = 'name',
  ALBUM_ID = 'albumId',
  IPFS_HASH = 'ipfsHash',
  PICTURE_IPFS_HASH = 'pictureIpfsHash',
  PICTURE_TYPE = 'pictureType',
  GENRE_ID = 'genreId',
  UPDATE_COUNT = 'updateCount',
  ALBUM = 'album',
  GENRE = 'genre',
  ARTIST_SONGS = 'artistSongs',
}
