/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { SongProperties } from './song.properties';

export function createTestSong() {
    return { 
      [SongProperties.ID]: 'ID',
      [SongProperties.NAME]: 'NAME',
      [SongProperties.ALBUM_ID]: 'ALBUM_ID',
      [SongProperties.IPFS_HASH]: 'IPFS_HASH',
      [SongProperties.PICTURE_IPFS_HASH]: 'PICTURE_IPFS_HASH',
      [SongProperties.PICTURE_TYPE]: 'PICTURE_TYPE',
      [SongProperties.GENRE_ID]: 'GENRE_ID',
      [SongProperties.UPDATE_COUNT]: 0, 
      [SongProperties.ALBUM]: undefined,
      [SongProperties.GENRE]: undefined,
      [SongProperties.ARTIST_SONGS]: [],
    };
}
