/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { IGenreForm } from './genre.form';
import { IArtistSongForm } from './artist-song.form';
import { IAlbumSongForm } from './album-song.form';

export interface ISongForm {
    id: FormControl<string | null | undefined>;
    name: FormControl<string>;
    ipfsHash: FormControl<string | null | undefined>;
    pictureIpfsHash: FormControl<string | null | undefined>;
    pictureType: FormControl<string | null | undefined>;
    genreId: FormControl<string>;
    updateCount: FormControl<number | null | undefined>;
    genre: FormGroup<IGenreForm>;
    artistSongs: FormArray<FormGroup<IArtistSongForm>>;
    albumSongs: FormArray<FormGroup<IAlbumSongForm>>;
}
