/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { IAlbumForm } from './album.form';
import { IArtistSongForm } from './artist-song.form';

export interface ISongForm {
    id: FormControl<string | null | undefined>;
    name: FormControl<string>;
    albumId: FormControl<string>;
    ipfsHash: FormControl<string | null | undefined>;
    pictureIpfsHash: FormControl<string | null | undefined>;
    updateCount: FormControl<number | null | undefined>;
    album: FormGroup<IAlbumForm>;
    artistSongs: FormArray<FormGroup<IArtistSongForm>>;
}
