/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR

export interface ISongUpsertRequestForm {
    id: FormControl<string | null | undefined>;
    name: FormControl<string>;
    albumIds: FormArray<FormControl<string>>;
    artistIds: FormArray<FormControl<string>>;
    genreId: FormControl<string>;
    ipfsHash: FormControl<string | null | undefined>;
    pictureIpfsHash: FormControl<string | null | undefined>;
    pictureType: FormControl<string | null | undefined>;
}
