/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { SongUpsertRequestProperties } from './song-upsert-request.properties';

export function createTestSongUpsertRequest() {
    return { 
      [SongUpsertRequestProperties.ID]: 'ID',
      [SongUpsertRequestProperties.NAME]: 'NAME',
      [SongUpsertRequestProperties.ALBUM_IDS]: 'ALBUM_IDS',
      [SongUpsertRequestProperties.ARTIST_IDS]: 'ARTIST_IDS',
      [SongUpsertRequestProperties.GENRE_ID]: 'GENRE_ID',
      [SongUpsertRequestProperties.IPFS_HASH]: 'IPFS_HASH',
      [SongUpsertRequestProperties.PICTURE_IPFS_HASH]: 'PICTURE_IPFS_HASH',
      [SongUpsertRequestProperties.PICTURE_TYPE]: 'PICTURE_TYPE', 
    };
}
