/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { ISongUpsertRequestForm } from './song-upsert-request.form';

export function SongUpsertRequestFormGroupFac(): FormGroup<ISongUpsertRequestForm> {
  return new FormGroup<ISongUpsertRequestForm>({
    id: new FormControl<string | null | undefined>(null),
    name: new FormControl<string>('', { validators: Validators.compose([Validators.required, Validators.minLength(1), Validators.maxLength(255)]), nonNullable: true }),
    albumIds: new FormArray<FormControl<string>>([]),
    artistIds: new FormArray<FormControl<string>>([], { validators: Validators.required }),
    genreId: new FormControl<string>('', { validators: Validators.compose([Validators.required, Validators.minLength(1), Validators.maxLength(255)]), nonNullable: true }),
    ipfsHash: new FormControl<string | null | undefined>(null, { validators: Validators.maxLength(255) } ),
    pictureIpfsHash: new FormControl<string | null | undefined>(null, { validators: Validators.maxLength(255) } ),
    pictureType: new FormControl<string | null | undefined>(null, { validators: Validators.maxLength(50) } ),
  });
}
