/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #endpoints-ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum Endpoints {
  images = 'media-webapi/api/image',
  media = 'media-webapi/api/media',
}
export interface IEndpoints {
  readonly images: string;
  readonly media: string;
}
