/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #index.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export * from './media-data-response.model';
export * from './media-data-response.properties';
export * from './media-data-response.test-obj-fac';
export * from './media-update-request.model';
export * from './media-update-request.properties';
export * from './media-update-request.test-obj-fac';
export * from './media-update-response.model';
export * from './media-update-response.properties';
export * from './media-update-response.test-obj-fac';
export * from './media-upload-request.model';
export * from './media-upload-request.properties';
export * from './media-upload-request.test-obj-fac';
export * from './media-upload-response.model';
export * from './media-upload-response.properties';
export * from './media-upload-response.test-obj-fac';
