/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { MediaDataResponseProperties } from './media-data-response.properties';

export function createTestMediaDataResponse() {
    return { 
      [MediaDataResponseProperties.IPFS_HASH]: 'IPFS_HASH',
      [MediaDataResponseProperties.FILE_SIZE]: 0,
      [MediaDataResponseProperties.FILE_NAME]: 'FILE_NAME',
      [MediaDataResponseProperties.REFERENCE_ID]: 'REFERENCE_ID',
      [MediaDataResponseProperties.REFERENCE_NAME]: 'REFERENCE_NAME', 
    };
}
