/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { MediaUpdateRequestProperties } from './media-update-request.properties';

export function createTestMediaUpdateRequest() {
    return { 
      [MediaUpdateRequestProperties.IPFS_HASH]: 'IPFS_HASH',
      [MediaUpdateRequestProperties.REFERENCE_NAME]: 'REFERENCE_NAME',
      [MediaUpdateRequestProperties.REFERENCE_TYPE]: 'REFERENCE_TYPE', 
    };
}
