/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { MediaUpdateResponseProperties } from './media-update-response.properties';

export function createTestMediaUpdateResponse() {
    return { 
      [MediaUpdateResponseProperties.IPFS_HASH]: 'IPFS_HASH',
      [MediaUpdateResponseProperties.REFERENCE_NAME]: 'REFERENCE_NAME',
      [MediaUpdateResponseProperties.REFERENCE_TYPE]: 'REFERENCE_TYPE', 
    };
}
