/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { MediaUploadRequestProperties } from './media-upload-request.properties';

export function createTestMediaUploadRequest() {
    return { 
      [MediaUploadRequestProperties.CONTENT]: 'CONTENT',
      [MediaUploadRequestProperties.FILE_NAME]: 'FILE_NAME',
      [MediaUploadRequestProperties.FILE_TYPE]: 'FILE_TYPE',
      [MediaUploadRequestProperties.REFERENCE_NAME]: 'REFERENCE_NAME',
      [MediaUploadRequestProperties.REFERENCE_TYPE]: 'REFERENCE_TYPE', 
    };
}
