/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum MediaUploadRequestProperties {
/**
 * This should be base64 encoded string
 */
  CONTENT = 'content',
  FILE_NAME = 'fileName',
  FILE_TYPE = 'fileType',
  REFERENCE_NAME = 'referenceName',
  REFERENCE_TYPE = 'referenceType',
}
