/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { MediaUploadResponseProperties } from './media-upload-response.properties';

export function createTestMediaUploadResponse() {
    return { 
      [MediaUploadResponseProperties.IPFS_HASH]: 'IPFS_HASH',
      [MediaUploadResponseProperties.FILE_SIZE]: 0, 
    };
}
