/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum MediaDataResponseProperties {
  IPFS_HASH = 'ipfsHash',
  FILE_SIZE = 'fileSize',
  FILE_NAME = 'fileName',
  FILE_TYPE = 'fileType',
  REFERENCE_TYPE = 'referenceType',
  REFERENCE_NAME = 'referenceName',
}
