/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { UploadFileResponseProperties } from './upload-file-response.properties';

export function createTestUploadFileResponse() {
    return { 
      [UploadFileResponseProperties.IPFS_HASH]: 'IPFS_HASH',
      [UploadFileResponseProperties.FILE_SIZE]: 0, 
    };
}
