/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #index.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export * from './customer-favorite-artist.form-group-fac';
export * from './customer-favorite-artist.form';
export * from './customer-favorite-artist.model';
export * from './customer-favorite-artist.properties';
export * from './customer-favorite-artist.test-obj-fac';
export * from './customer-favorite-genre.form-group-fac';
export * from './customer-favorite-genre.form';
export * from './customer-favorite-genre.model';
export * from './customer-favorite-genre.properties';
export * from './customer-favorite-genre.test-obj-fac';
export * from './customer-purchase.form-group-fac';
export * from './customer-purchase.form';
export * from './customer-purchase.model';
export * from './customer-purchase.properties';
export * from './customer-purchase.test-obj-fac';
export * from './customer.form-group-fac';
export * from './customer.form';
export * from './customer.model';
export * from './customer.properties';
export * from './customer.test-obj-fac';
