/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum AlbumProperties {
  ID = 'id',
  NAME = 'name',
  ARTIST_ID = 'artistId',
  SONG_COUNT = 'songCount',
  PICTURE_ID = 'pictureId',
  CREATED_BY = 'createdBy',
  UPDATED_BY = 'updatedBy',
  CREATED_ON_UTC = 'createdOnUtc',
  UPDATED_ON_UTC = 'updatedOnUtc',
  UPDATE_COUNT = 'updateCount',
  ARTIST = 'artist',
  SONGS = 'songs',
  PICTURE = 'picture',
}
