/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { AlbumProperties } from './album.properties';

export function createTestAlbum() {
    return { 
      [AlbumProperties.ID]: 'ID',
      [AlbumProperties.NAME]: 'NAME',
      [AlbumProperties.ARTIST_ID]: 'ARTIST_ID',
      [AlbumProperties.SONG_COUNT]: 0,
      [AlbumProperties.PICTURE_ID]: 'PICTURE_ID',
      [AlbumProperties.CREATED_BY]: 'CREATED_BY',
      [AlbumProperties.UPDATED_BY]: 'UPDATED_BY',
      [AlbumProperties.CREATED_ON_UTC]: new Date(),
      [AlbumProperties.UPDATED_ON_UTC]: new Date(),
      [AlbumProperties.UPDATE_COUNT]: 0, 
      [AlbumProperties.ARTIST]: undefined,
      [AlbumProperties.SONGS]: [],
      [AlbumProperties.PICTURE]: undefined,
    };
}
