/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IAlbumForm } from './album.form';
import { IArtistForm } from './artist.form';
import { ArtistFormGroupFac } from './artist.form-group-fac';
import { IAlbumSongForm } from './album-song.form';
import { IPictureForm } from './picture.form';
import { PictureFormGroupFac } from './picture.form-group-fac';

export function AlbumFormGroupFac(): FormGroup<IAlbumForm> {
  return new FormGroup<IAlbumForm>({
    id: new FormControl<string | null | undefined>(null),
    name: new FormControl<string>('', { validators: Validators.compose([Validators.required, Validators.minLength(1), Validators.maxLength(255)]), nonNullable: true }),
    artistId: new FormControl<string>('', { validators: Validators.required, nonNullable: true } ),
    songCount: new FormControl<number | null | undefined>(null),
    pictureId: new FormControl<string | null | undefined>(null),
    createdBy: new FormControl<string>('', { validators: Validators.compose([Validators.required, Validators.minLength(1)]), nonNullable: true }),
    updatedBy: new FormControl<string | null | undefined>(null),
    createdOnUtc: new FormControl<Date | null | undefined>(null),
    updatedOnUtc: new FormControl<Date | null | undefined>(null),
    updateCount: new FormControl<number | null | undefined>(null),
    artist: new FormGroup<IArtistForm>(ArtistFormGroupFac().controls),
    songs: new FormArray<FormGroup<IAlbumSongForm>>([]),
    picture: new FormGroup<IPictureForm>(PictureFormGroupFac().controls),
  });
}
