/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IArtistForm } from './artist.form';
import { IArtistGenreForm } from './artist-genre.form';
import { IAlbumForm } from './album.form';
import { IArtistSongForm } from './artist-song.form';
import { IPictureForm } from './picture.form';
import { PictureFormGroupFac } from './picture.form-group-fac';

export function ArtistFormGroupFac(): FormGroup<IArtistForm> {
  return new FormGroup<IArtistForm>({
    id: new FormControl<string | null | undefined>(null),
    name: new FormControl<string>('', { validators: Validators.compose([Validators.required, Validators.minLength(2), Validators.maxLength(255)]), nonNullable: true }),
    stageName: new FormControl<string>('', { validators: Validators.compose([Validators.required, Validators.minLength(2), Validators.maxLength(255)]), nonNullable: true }),
    email: new FormControl<string>('', { validators: Validators.compose([Validators.required, Validators.email, Validators.minLength(2), Validators.maxLength(255)]), nonNullable: true }),
    albumCount: new FormControl<number | null | undefined>(null),
    songCount: new FormControl<number | null | undefined>(null),
    pictureId: new FormControl<string | null | undefined>(null),
    createdBy: new FormControl<string>('', { validators: Validators.compose([Validators.required, Validators.minLength(1)]), nonNullable: true }),
    updatedBy: new FormControl<string | null | undefined>(null),
    createdOnUtc: new FormControl<Date | null | undefined>(null),
    updatedOnUtc: new FormControl<Date | null | undefined>(null),
    updateCount: new FormControl<number | null | undefined>(null),
    genres: new FormArray<FormGroup<IArtistGenreForm>>([]),
    albums: new FormArray<FormGroup<IAlbumForm>>([]),
    artistSongs: new FormArray<FormGroup<IArtistSongForm>>([]),
    picture: new FormGroup<IPictureForm>(PictureFormGroupFac().controls),
  });
}
