/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { IArtistGenre } from './artist-genre.model';
import { IAlbum } from './album.model';
import { IArtistSong } from './artist-song.model';
import { IPicture } from './picture.model';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface IArtist {
  id?: string | null;
  name?: string;
  stageName?: string;
  email?: string;
  albumCount?: number | null;
  songCount?: number | null;
  pictureId?: string | null;
  createdBy?: string;
  updatedBy?: string | null;
  createdOnUtc?: Date | null;
  updatedOnUtc?: Date | null;
  updateCount?: number | null;
  genres?: Partial<IArtistGenre[]>;
  albums?: Partial<IAlbum[]>;
  artistSongs?: Partial<IArtistSong[]>;
  picture?: Partial<IPicture>;
}
