/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #endpoints-ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum Endpoints {
  albums = 'artists-odata/odata/v1/Albums',
  artists = 'artists-odata/odata/v1/Artists',
  genres = 'artists-odata/odata/v1/Genres',
  songs = 'artists-odata/odata/v1/Songs',
}
export interface IEndpoints {
  readonly albums: string;
  readonly artists: string;
  readonly genres: string;
  readonly songs: string;
}
