/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { ICustomerFavoriteArtistForm } from './customer-favorite-artist.form';
import { ICustomerFavoriteGenreForm } from './customer-favorite-genre.form';
import { ICustomerPurchaseForm } from './customer-purchase.form';

export interface ICustomerForm {
    id: FormControl<string | null | undefined>;
    name: FormControl<string>;
    email: FormControl<string>;
    createdBy: FormControl<string>;
    updatedBy: FormControl<string | null | undefined>;
    createdOnUtc: FormControl<Date | null | undefined>;
    updatedOnUtc: FormControl<Date | null | undefined>;
    updateCount: FormControl<number | null | undefined>;
    favoriteArtists: FormArray<FormGroup<ICustomerFavoriteArtistForm>>;
    favoriteGenres: FormArray<FormGroup<ICustomerFavoriteGenreForm>>;
    purchases: FormArray<FormGroup<ICustomerPurchaseForm>>;
}
