/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { CustomerFavoriteGenreProperties } from './customer-favorite-genre.properties';

export function createTestCustomerFavoriteGenre() {
    return { 
      [CustomerFavoriteGenreProperties.ID]: 'ID',
      [CustomerFavoriteGenreProperties.NAME]: 'NAME',
      [CustomerFavoriteGenreProperties.CUSTOMER_ID]: 'CUSTOMER_ID',
      [CustomerFavoriteGenreProperties.CREATED_BY]: 'CREATED_BY',
      [CustomerFavoriteGenreProperties.UPDATED_BY]: 'UPDATED_BY',
      [CustomerFavoriteGenreProperties.CREATED_ON_UTC]: new Date(),
      [CustomerFavoriteGenreProperties.UPDATED_ON_UTC]: new Date(),
      [CustomerFavoriteGenreProperties.UPDATE_COUNT]: 0, 
      [CustomerFavoriteGenreProperties.CUSTOMER]: undefined,
    };
}
