/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { ICustomerFavoriteArtistForm } from './customer-favorite-artist.form';
import { ICustomerForm } from './customer.form';
import { CustomerFormGroupFac } from './customer.form-group-fac';

export function CustomerFavoriteArtistFormGroupFac(): FormGroup<ICustomerFavoriteArtistForm> {
  return new FormGroup<ICustomerFavoriteArtistForm>({
    id: new FormControl<string | null | undefined>(null),
    artistsName: new FormControl<string>('', { validators: Validators.compose([Validators.required, Validators.minLength(2), Validators.maxLength(255)]), nonNullable: true }),
    artistId: new FormControl<string>('', { validators: Validators.required, nonNullable: true } ),
    customerId: new FormControl<string>('', { validators: Validators.required, nonNullable: true } ),
    createdBy: new FormControl<string>('', { validators: Validators.compose([Validators.required, Validators.minLength(1)]), nonNullable: true }),
    updatedBy: new FormControl<string | null | undefined>(null),
    createdOnUtc: new FormControl<Date | null | undefined>(null),
    updatedOnUtc: new FormControl<Date | null | undefined>(null),
    updateCount: new FormControl<number | null | undefined>(null),
    customer: new FormGroup<ICustomerForm>(CustomerFormGroupFac().controls),
  });
}
