/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #endpoints-ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum Endpoints {
  customerPurchases = 'customers-odata/odata/v1/CustomerPurchases',
  customers = 'customers-odata/odata/v1/Customers',
}
export interface IEndpoints {
  readonly customerPurchases: string;
  readonly customers: string;
}
