/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { CustomerFavoriteArtistProperties } from './customer-favorite-artist.properties';

export function createTestCustomerFavoriteArtist() {
    return { 
      [CustomerFavoriteArtistProperties.ID]: 'ID',
      [CustomerFavoriteArtistProperties.ARTISTS_NAME]: 'ARTISTS_NAME',
      [CustomerFavoriteArtistProperties.ARTIST_ID]: 'ARTIST_ID',
      [CustomerFavoriteArtistProperties.CUSTOMER_ID]: 'CUSTOMER_ID',
      [CustomerFavoriteArtistProperties.UPDATE_COUNT]: 0, 
      [CustomerFavoriteArtistProperties.CUSTOMER]: undefined,
    };
}
