/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup } from '@angular/forms'; //NOSONAR
import { ICustomerForm } from './customer.form';

export interface ICustomerPurchaseForm {
    id: FormControl<string | null | undefined>;
    artistsName: FormControl<string>;
    artistId: FormControl<string>;
    songName: FormControl<string>;
    transactionNum: FormControl<string>;
    rating: FormControl<number | null | undefined>;
    songId: FormControl<string>;
    customerId: FormControl<string>;
    updateCount: FormControl<number | null | undefined>;
    customer: FormGroup<ICustomerForm>;
}
