/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { CustomerProperties } from './customer.properties';

export function createTestCustomer() {
    return { 
      [CustomerProperties.ID]: 'ID',
      [CustomerProperties.NAME]: 'NAME',
      [CustomerProperties.EMAIL]: 'customer@email.org',
      [CustomerProperties.UPDATE_COUNT]: 0, 
      [CustomerProperties.FAVORITE_ARTISTS]: [],
      [CustomerProperties.FAVORITE_GENRES]: [],
      [CustomerProperties.PURCHASES]: [],
    };
}
