/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { CustomerUpsertRequestProperties } from './customer-upsert-request.properties';

export function createTestCustomerUpsertRequest() {
    return { 
      [CustomerUpsertRequestProperties.ID]: 'ID',
      [CustomerUpsertRequestProperties.NAME]: 'NAME',
      [CustomerUpsertRequestProperties.EMAIL]: 'customer-upsert-request@email.org', 
    };
}
