/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model-properties.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum CustomerFavoriteArtistProperties {
  ID = 'id',
  ARTISTS_NAME = 'artistsName',
  ARTIST_ID = 'artistId',
  CUSTOMER_ID = 'customerId',
  UPDATE_COUNT = 'updateCount',
  CUSTOMER = 'customer',
}
