/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #test-object-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { ProblemDetailsProperties } from './problem-details.properties';

export function createTestProblemDetails() {
    return { 
      [ProblemDetailsProperties.TYPE]: 'TYPE',
      [ProblemDetailsProperties.TITLE]: 'TITLE',
      [ProblemDetailsProperties.STATUS]: 0,
      [ProblemDetailsProperties.DETAIL]: 'DETAIL',
      [ProblemDetailsProperties.INSTANCE]: 'INSTANCE', 
    };
}
