/* eslint-disable no-useless-escape */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #form-group-factory.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
import { FormControl, FormArray, FormGroup, Validators } from '@angular/forms'; //NOSONAR
import { IProblemDetailsForm } from './problem-details.form';

export function ProblemDetailsFormGroupFac(): FormGroup<IProblemDetailsForm> {
  return new FormGroup<IProblemDetailsForm>({
    type: new FormControl<string | null | undefined>(null),
    title: new FormControl<string | null | undefined>(null),
    status: new FormControl<number | null | undefined>(null),
    detail: new FormControl<string | null | undefined>(null),
    instance: new FormControl<string | null | undefined>(null),
  });
}
