/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { IArtist } from './artist.model';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface IArtistGenre {
  id?: string | null;
  name?: string;
  artistId?: string;
  createdBy?: string;
  updatedBy?: string | null;
  createdOnUtc?: Date | null;
  updatedOnUtc?: Date | null;
  updateCount?: number | null;
  artist?: Partial<IArtist>;
}
