/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #endpoints-ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */
/* tslint:disable */
export enum Endpoints {
  albums = '/odata/v1/Albums',
  artists = '/odata/v1/Artists',
  pictures = '/odata/v1/Pictures',
  songs = '/odata/v1/Songs',
}
export interface IEndpoints {
  readonly albums: string;
  readonly artists: string;
  readonly pictures: string;
  readonly songs: string;
}
