/* istanbul ignore file */
/**
 * This file is generated by the openapi-ts-generator
 * #model.ts.hbs
 * For issues or feature request, visit the repo: https://github.com/ikemtz/openapi-ts-generator
 * Do not edit.
 */

import { IAlbum } from './album.model';
import { IPicture } from './picture.model';
import { IArtistSong } from './artist-song.model';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface ISong {
  id?: string | null;
  name?: string;
  albumId?: string;
  pictureId?: string | null;
  createdBy?: string;
  updatedBy?: string | null;
  createdOnUtc?: Date | null;
  updatedOnUtc?: Date | null;
  updateCount?: number | null;
  album?: Partial<IAlbum>;
  picture?: Partial<IPicture>;
  artistSongs?: Partial<IArtistSong[]>;
}
